// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniSys.Database.Data;

namespace UniSys.Database.Migrations
{
    [DbContext(typeof(UniSystDbContext))]
    [Migration("20190402114317_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniSys.Database.Data.Models.Users.Lecturer", b =>
                {
                    b.Property<int>("LecturerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthDate");

                    b.Property<string>("Faculty")
                        .IsUnicode(true);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("Gender");

                    b.Property<string>("Image");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("PersonalNumber")
                        .HasMaxLength(10)
                        .IsUnicode(true);

                    b.Property<string>("Region");

                    b.Property<string>("Students");

                    b.Property<string>("Subjects");

                    b.Property<string>("Title")
                        .IsUnicode(true);

                    b.HasKey("LecturerId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("UniSys.Database.Data.Models.Users.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthDate");

                    b.Property<string>("Faculty")
                        .IsUnicode(true);

                    b.Property<string>("FacultyNumber");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("Gender");

                    b.Property<string>("Image");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("PersonalNumber")
                        .HasMaxLength(10);

                    b.Property<string>("Region")
                        .IsUnicode(true);

                    b.Property<string>("Specialty")
                        .IsUnicode(true);

                    b.Property<int?>("SubjectId");

                    b.HasKey("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UniSys.Database.Data.Models.Users.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LecturerId");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.HasKey("SubjectId");

                    b.HasIndex("LecturerId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("UniSys.Database.Data.Models.Users.Student", b =>
                {
                    b.HasOne("UniSys.Database.Data.Models.Users.Subject")
                        .WithMany("Students")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("UniSys.Database.Data.Models.Users.Subject", b =>
                {
                    b.HasOne("UniSys.Database.Data.Models.Users.Lecturer")
                        .WithMany("SubjectCollection")
                        .HasForeignKey("LecturerId");
                });
#pragma warning restore 612, 618
        }
    }
}
